### ISSUE TITLE
Change tab color for current editor

### ISSUE THREAD

**Issue by andrewrynhard** [ryanolsonx/vscode-seoul-theme#1]
Hey! First off thank you for porting this to vscode! I did have one thing I'd like to see if you would consider. The tab color for the currently active editor seems backwards to me. In dark mode, the current tab blends matches the dark background and non-active editors are highlighted.

<img width="294" alt="Screen Shot 2019-05-03 at 2 18 28 PM" src="https://user-images.githubusercontent.com/3383143/57166313-9ac74b00-6dae-11e9-94a7-97a4bdb5c06f.png">

This causes me a lot of confusion and slows me down when navigating my editors. Would it be possible to switch the behavior to highlighting the current active editor with the lighter version? Thanks!

**Comment by ryanolsonx** [comment]
I'll think about a better look :)

**Comment by ryanolsonx** [comment]
In looking at this issue, I have found that I disagree with you. Luckily, I can provide you a snippet of config that you can put in your settings.json file.

```json
"workbench.colorCustomizations": {
        "[Seoul Dark]": {
            "editorGroupHeader.tabsBackground": "#4b4b4b",
            "tab.inactiveBackground": "#4b4b4b",
            "tab.activeBackground": "#757575"
        }
    }
```

This will change the look and feel as you requested. If you need any other help, please let me know.

**Comment by andrewrynhard** [comment]
Might be nice to have this as an option in the settings.

**Comment by ryanolsonx** [comment]
That would be nice. From what I understand with themes, you can't configure themes.

**Comment by andrewrynhard** [comment]
Bummer.
